# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0004_studentapplying'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicApplying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20, null=True)),
                ('last', models.CharField(max_length=20, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('identity', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(max_length=20, null=True)),
                ('college', models.CharField(max_length=20, null=True)),
                ('language', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
