# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0007_businessentapplying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='government',
            name='institution_adress',
        ),
        migrations.AddField(
            model_name='government',
            name='Contact_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='government',
            name='Streect_adress',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='government',
            name='acceptance_doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='government',
            name='institution_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='government',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='government',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='institution_location',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='institution_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
